module.exports = {
    token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFybmlzaCIsInVzZXJuYW1lIjoiY2hhcm5pc2giLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTE0MDc2MDMsImV4cCI6MTY5Mzk5OTYwM30.GRlV3Xot8mN7nRmloE8t_Y-LkzKcrNiOarzRmcaUStI"
  };